# make it explicit that we favor the new container-based travis workers
sudo: false

language: python

cache:
  apt: true
  directories:
  - $HOME/.cache/pip
  - $HOME/.ccache

dist: trusty

env:
  global:
    # Directory where tests are run from
    - TEST_DIR=/tmp/operalib
    - OMP_NUM_THREADS=4
    - OPENBLAS_NUM_THREADS=4
    - MODULE=operalib
matrix:
  include:
    # This environment tests that scikit-learn can be built against
    # versions of numpy, scipy with ATLAS that comes with Ubuntu Trusty 14.04
    # i.e. numpy 1.8.2 and scipy 0.13.3
    - env: DISTRIB="ubuntu" PYTHON_VERSION="2.7" CYTHON_VERSION="0.23.5"
           COVERAGE=true
      if: type != cron
      addons:
        apt:
          packages:
            - python-scipy
            - python-tk
            - libatlas3-base
            - libatlas-dev
            - gfortran
            - libblas-dev
            - liblapack-dev
    # Python 3.4 build
    - env: DISTRIB="conda" PYTHON_VERSION="3.4" INSTALL_MKL="false"
           NUMPY_VERSION="1.10" SCIPY_VERSION="0.16" CYTHON_VERSION="0.25"
           PILLOW_VERSION="4.0" COVERAGE=true
      if: type != cron
      addons:
        apt:
          packages:
            - gfortran
            - libblas-dev
            - liblapack-dev
    # This environment tests the newest supported Anaconda release (5.0.0)
    # It also runs tests requiring Pandas and PyAMG
    - env: DISTRIB="conda" PYTHON_VERSION="3.6" INSTALL_MKL="true"
           NUMPY_VERSION="1.14" SCIPY_VERSION="1.0" PANDAS_VERSION="0.20"
           CYTHON_VERSION="0.26" PYAMG_VERSION="3.3" PILLOW_VERSION="4.3"
           COVERAGE=true
           CHECK_PYTEST_SOFT_DEPENDENCY="true" TEST_DOCSTRINGS="true"
      if: type != cron
      addons:
        apt:
          packages:
            - gfortran
            - libblas-dev
            - liblapack-dev
    # flake8 linting on diff wrt common ancestor with upstream/master
    - env: RUN_FLAKE8="true" SKIP_TESTS="true"
           DISTRIB="conda" PYTHON_VERSION="3.5" INSTALL_MKL="true"
           NUMPY_VERSION="1.13" SCIPY_VERSION="0.19"
           CYTHON_VERSION="0.26" COVERAGE=true
           CHECK_PYTEST_SOFT_DEPENDENCY="true" TEST_DOCSTRINGS="true"
      if: type != cron
      addons:
        apt:
          packages:
            - gfortran
            - libblas-dev
            - liblapack-dev
    # This environment tests scikit-learn against numpy and scipy master
    # installed from their CI wheels in a virtualenv with the Python
    # interpreter provided by travis.
    -  python: 3.6
       env: DISTRIB="scipy-dev-wheels"
       if: type = cron
       addons:
         apt:
           packages:
             - gfortran
             - libblas-dev
             - liblapack-dev

# Workaround for suitesparse and control
before_install:
  - pushd ${HOME}
  - wget http://faculty.cse.tamu.edu/davis/SuiteSparse/SuiteSparse-4.5.3.tar.gz
  - tar -xf SuiteSparse-4.5.3.tar.gz
  - export CVXOPT_SUITESPARSE_SRC_DIR=$(pwd)/SuiteSparse]
  - popd
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib64/:/usr/lib/x86_64-linux-gnu/
install: source ci_scripts/install.sh
script: bash ci_scripts/test.sh
after_success: source ci_scripts/success.sh
